plugins {
    id "com.android.application"
}

android {
    namespace "com.epicenterguy.dokihanja"
    compileSdk 35

    defaultConfig {
        applicationId "com.epicenterguy.dokihanja"
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName "0.2.0"
    }

    buildTypes {
        debug {
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
